#!/usr/bin/env bash
set -euo pipefail

# new-project.sh <project_dir> [backend_internal_port] [frontend_internal_port]
# Aloca portas livres nas faixas definidas pela plataforma e escreve .env

PROJECT_DIR=${1:-.}
BACK_INTERNAL=${2:-8000}
FRONT_INTERNAL=${3:-80}

BACK_START=8001
BACK_END=8599
FRONT_START=3000
FRONT_END=3499

ss_cmd() {
  ss -ltn 2>/dev/null || netstat -ltn 2>/dev/null
}

find_free_port() {
  local start=$1 end=$2
  for p in $(seq $start $end); do
    if ! ss_cmd | awk '{print $4}' | sed -E 's/.*[:]//g' | grep -x "$p" >/dev/null 2>&1; then
      echo $p
      return 0
    fi
  done
  return 1
}

mkdir -p "$PROJECT_DIR"

BACK_PORT=$(find_free_port $BACK_START $BACK_END) || { echo "No free backend ports in range $BACK_START-$BACK_END" >&2; exit 1; }
FRONT_PORT=$(find_free_port $FRONT_START $FRONT_END) || { echo "No free frontend ports in range $FRONT_START-$FRONT_END" >&2; exit 1; }

ENV_FILE="$PROJECT_DIR/.env"
# Remove old entries and append
if [ -f "$ENV_FILE" ]; then
  sed -i '/^BACKEND_PORT=/d' "$ENV_FILE" || true
  sed -i '/^FRONTEND_PORT=/d' "$ENV_FILE" || true
fi
{
  echo "# Generated by dev-workspace/scripts/new-project.sh"
  echo "BACKEND_PORT=$BACK_PORT"
  echo "FRONTEND_PORT=$FRONT_PORT"
  # internal ports used inside the container (defaults can be overridden by args)
  echo "APP_INTERNAL_PORT=$BACK_INTERNAL"
  echo "FRONT_INTERNAL=$FRONT_INTERNAL"
} >> "$ENV_FILE"

# Ensure docker-compose uses external dev-workspace-net
DC_FILE="$PROJECT_DIR/docker-compose.yml"
if [ -f "$DC_FILE" ]; then
  if command -v yq >/dev/null 2>&1; then
    # Structural parsing via yq (Go or Python version compatible fallback block)
    yq -i '.networks["dev-workspace-net"].external = true | .networks["dev-workspace-net"].name = "dev-workspace-net"' "$DC_FILE" 2>/dev/null || \
      yq -i -y '.networks."dev-workspace-net".external = true | .networks."dev-workspace-net".name = "dev-workspace-net"' "$DC_FILE" 2>/dev/null
  else
    # Fallback to textual parsing
    if ! grep -q "dev-workspace-net" "$DC_FILE"; then
      cat >> "$DC_FILE" <<'EOF'

networks:
  dev-workspace-net:
    external: true
    name: dev-workspace-net
EOF
    fi
  fi
fi

echo "Allocated ports: BACKEND_PORT=$BACK_PORT FRONTEND_PORT=$FRONT_PORT"
echo "Wrote $ENV_FILE"

exit 0
